### ISSUE TITLE
Support Python 3 and run advisor with PyCharm

### ISSUE THREAD

**Issue by codlife** [tobegit3hub/advisor#3]
/usr/bin/python3.5 /home/hadoop/PycharmProjects/advisor/advisor_server/manage.py runserver 0.0.0.0:8000
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1339688840>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/hadoop/PycharmProjects/advisor/advisor_server/advisor/urls.py", line 29, in <module>
    url(r'^suggestion/', include('suggestion.urls')),
  File "/usr/local/lib/python3.5/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/hadoop/PycharmProjects/advisor/advisor_server/suggestion/urls.py", line 2, in <module>
    from . import views
  File "/home/hadoop/PycharmProjects/advisor/advisor_server/suggestion/views.py", line 16, in <module>
    from suggestion.algorithm.random_search import RandomSearchAlgorithm
  File "/home/hadoop/PycharmProjects/advisor/advisor_server/suggestion/algorithm/random_search.py", line 6, in <module>
    from base_algorithm import BaseSuggestionAlgorithm
ImportError: No module named 'base_algorithm'

**Comment by codlife** [comment]
python3.5 is ok, just with some import error
such as:  
`from random_search import RandomSearchAlgorithm`
to
`from .random_search import RandomSearchAlgorithm`
will be ok

**Comment by tobegit3hub** [comment]
Thanks @codlife for your reporting. This should be changed to run in both Python 2 and Python 3.

**Comment by impredicative** [comment]
Any status update for Python 3.7 support? Thanks.

**Comment by tobegit3hub** [comment]
I don't test it yet. It's contribution welcome and free feel to send PR.

**Comment by andrewssobral** [comment]
Tested on Python 3.6.6 and I got:
```
macbook:~ andrewssobral$ advisor_admin server start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/advisor_admin", line 7, in <module>
    from advisor_client.commandline.admin_command import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/advisor_client/commandline/admin_command.py", line 110
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax
macbook:~ andrewssobral$ 
```
Any status update for this? Thanks

**Comment by mygao8** [comment]
> Tested on Python 3.6.6 and I got:
> 
> ```
> macbook:~ andrewssobral$ advisor_admin server start
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/advisor_admin", line 7, in <module>
>     from advisor_client.commandline.admin_command import main
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/advisor_client/commandline/admin_command.py", line 110
>     except subprocess.CalledProcessError, e:
>                                         ^
> SyntaxError: invalid syntax
> macbook:~ andrewssobral$ 
> ```
> 
> Any status update for this? Thanks

Change the comma to as. Then it's OK

**Comment by tobegit3hub** [comment]
Thanks @andresmore and @mygao8 . I will update this soon and need more test in Python 2.7 and 3.6 in the future.
