### ISSUE TITLE
pip install error. 

### ISSUE THREAD

**Issue by ideaRunner** [tobegit3hub/advisor#33]
Hi, there.

Is anything wrong with the pip installation? 
I tried different pip mirror source even with or without conda, python2 and python3
But I got similar error and it will install a package named unknown.
Anyone same as me?

``` shell
(master)⚡ [130] % pip install advisor --user
Collecting advisor
  Downloading https://files.pythonhosted.org/packages/c1/fd/5cf49e6fbf34e3879ac12561e258827a5aa422469fca6faf3a17aaf3e7a9/advisor-0.1.6.tar.gz
  Running setup.py (path:/tmp/pip-install-v6LivQ/advisor/setup.py) egg_info for package advisor produced metadata for project name unknown. Fix your #egg=advisor fragments.
Building wheels for collected packages: unknown, unknown
  Running setup.py bdist_wheel for unknown ... done
  Stored in directory: /home/myname/.cache/pip/wheels/97/10/41/fd24dfce3d66fe01c1a4ee2fca1e33c9dc5e68eef0d6177d88
  Running setup.py bdist_wheel for unknown ... error
  Complete output from command /home/tools/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v6LivQ/unknown/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-JAGH_G --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-install-v6LivQ/unknown/setup.py'
  
  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown
  Complete output from command /home/tools/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v6LivQ/unknown/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-install-v6LivQ/unknown/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
Installing collected packages: unknown
Successfully installed unknown-0.0.0
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ideaRunner** [comment]
Solved by install from source.
