### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by embersa** [tobegit3hub/advisor#34]
same question 

macbook:~ andrewssobral$ advisor_admin server start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/advisor_admin", line 7, in <module>
    from advisor_client.commandline.admin_command import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/advisor_client/commandline/admin_command.py", line 110
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax
macbook:~ andrewssobral$ 
Any status update for this? Thanks

**Comment by tobegit3hub** [comment]
It would be the problem of Python3. We will address this and fix it soon.
