### ISSUE TITLE
advisor_admin server start not work(python version)

### ISSUE THREAD

**Issue by fairleehu** [tobegit3hub/advisor#40]
When i run advisor_admin server start, it has a SyntaxError an invalid syntax in the site-packages/advisor-0.1.6-py3.6.egg/advisor_client/commandline/admin_command.py

def is_server_running():

  command = "docker ps |grep 'tobegit3hub/advisor'"
  print("Run the command: {}".format(command))

  try:
    command_output = subprocess.check_output(command, shell=True)

    if command_output != "":
      return True

  **except subprocess.CalledProcessError, e:**
    if e.output == "":
      pass
    else:
      print("Get error: {}".format(e.output))
    return False

**Comment by divenpuke** [comment]
I think I have the same problem.

From git bash after "pip install advisor". Which installed ok after upgrading python to newest version. Didn't work with 2.7.

> $ advisor_admin server start
> Traceback (most recent call last):
>   File "C:\Users\JasonM\AppDat

a\Local\Programs\Python\Python37-32\Scripts\advisor_admin-script.py", line 11, in <module>
    load_entry_point('advisor-clients==0.1.4.1', 'console_scripts', 'advisor_admin')()
  File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\advisor_client\commandline\admin_command.py", line 110
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax


Help?

**Comment by yinchuandong** [comment]
> I think I have the same problem.
> 
> From git bash after "pip install advisor". Which installed ok after upgrading python to newest version. Didn't work with 2.7.
> 
> > $ advisor_admin server start
> > Traceback (most recent call last):
> > File "C:\Users\JasonM\AppDat
> 
> a\Local\Programs\Python\Python37-32\Scripts\advisor_admin-script.py", line 11, in 
> load_entry_point('advisor-clients==0.1.4.1', 'console_scripts', 'advisor_admin')()
> File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 489, in load_entry_point
> return get_distribution(dist).load_entry_point(group, name)
> File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 2793, in load_entry_point
> return ep.load()
> File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 2411, in load
> return self.resolve()
> File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 2417, in resolve
> module = **import**(self.module_name, fromlist=['**name**'], level=0)
> File "c:\users\jasonm\appdata\local\programs\python\python37-32\lib\site-packages\advisor_client\commandline\admin_command.py", line 110
> except subprocess.CalledProcessError, e:
> ^
> SyntaxError: invalid syntax
> 
> Help?

have the same problem for python 3.7.

**Comment by 15586233385** [comment]
I get the same problem, my version of python is 3.6.

**Comment by arminzirak** [comment]
Same problem with python3.8

**Comment by risemeup** [comment]
> I get the same problem, my version of python is 3.6.
hello,I have the same problem with python3.6,have you solve it？

**Comment by bhishanpdl** [comment]
I have same problem with python 3.7.

# Installation
```
1. download folder from pypi: https://pypi.org/project/advisor/#files
2. then install it:   python setup.py install



Then,
advisor_admin server start
```

# Platform
- Macos catalina
- miniconda3 environment called "expl" with python 3.7

# Error
```
$ advisor_admin server start
Traceback (most recent call last):
  File "/Users/poudel/opt/miniconda3/envs/expl/bin/advisor_admin", line 33, in <module>
    sys.exit(load_entry_point('advisor==0.1.6', 'console_scripts', 'advisor_admin')())
  File "/Users/poudel/opt/miniconda3/envs/expl/bin/advisor_admin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/poudel/opt/miniconda3/envs/expl/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/Users/poudel/opt/miniconda3/envs/expl/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/poudel/opt/miniconda3/envs/expl/lib/python3.7/site-packages/advisor-0.1.6-py3.7.egg/advisor_client/commandline/admin_command.py", line 110
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax
```

**Comment by tobegit3hub** [comment]
This has been fixed in https://github.com/tobegit3hub/advisor/pull/21 .

Please check your code in line 110 of admin_command.py and make sure it is up-to-date.
