### ISSUE TITLE
Installation of advisor with command "pip3 install advisor" failed

### ISSUE THREAD

**Issue by duni123** [tobegit3hub/advisor#41]
Installation of advisor with command "pip3 install advisor" failed, but with command "pip2 install advisor" succeeded. Whether the advisor is currently only compatible with python2 and not python3.

**Comment by duni123** [comment]
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/python3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/usr/local/python3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/python3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 928, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/python3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 461, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/python3/lib/python3.6/site-packages/pip/_internal/wheel.py", line 434, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: advisor .dist-info directory not found

**Comment by wzmxd** [comment]
Finally find out the reason that there were 2 wheel files after the bulding finished. I suggest you can try this @duni123 ,
1. Go [PyPi](https://pypi.org/project/advisor/#files) to download the lastest version and untar it
2. Type `cd` command in terminal, change your current directory where the untarred files located 
3. Type `python setup.py install` then hit ENTER

then you shall find it appear in package list.

**Comment by wzmxd** [comment]
Also found a syntax mistake in `advisor_client/commandline/admin_command.py` line `110`, which is

`except subprocess.CalledProcessError, e`

and should be

`except subprocess.CalledProcessError as e`

**Comment by jiaojiaoguan** [comment]
> Finally find out the reason that there were 2 wheel files after the bulding finished. I suggest you can try this @duni123 ,
> 
> 1. Go [PyPi](https://pypi.org/project/advisor/#files) to download the lastest version and untar it
> 2. Type `cd` command in terminal, change your current directory where the untarred files located
> 3. Type `python setup.py install` then hit ENTER
> 
> then you shall find it appear in package list.

when I typed python setup.py, it appeared some error. "python setup.py install" is ok
